export const numBlackArray = [
  { num: 'A', color: 'black', open: false, first: false, jug: false },
  { num: '2', color: 'black', open: false, first: false, jug: false },
  { num: '3', color: 'black', open: false, first: false, jug: false },
  { num: '4', color: 'black', open: false, first: false, jug: false },
  { num: '5', color: 'black', open: false, first: false, jug: false },
  { num: '6', color: 'black', open: false, first: false, jug: false },
  { num: '7', color: 'black', open: false, first: false, jug: false },
  { num: '8', color: 'black', open: false, first: false, jug: false },
  { num: '9', color: 'black', open: false, first: false, jug: false },
  { num: '10', color: 'black', open: false, first: false, jug: false },
  { num: 'J', color: 'black', open: false, first: false, jug: false },
  { num: 'Q', color: 'black', open: false, first: false, jug: false },
  { num: 'K', color: 'black', open: false, first: false, jug: false },
];

export const numRedArray = [
  { num: 'A', color: 'red', open: false, first: false, jug: false },
  { num: '2', color: 'red', open: false, first: false, jug: false },
  { num: '3', color: 'red', open: false, first: false, jug: false },
  { num: '4', color: 'red', open: false, first: false, jug: false },
  { num: '5', color: 'red', open: false, first: false, jug: false },
  { num: '6', color: 'red', open: false, first: false, jug: false },
  { num: '7', color: 'red', open: false, first: false, jug: false },
  { num: '8', color: 'red', open: false, first: false, jug: false },
  { num: '9', color: 'red', open: false, first: false, jug: false },
  { num: '10', color: 'red', open: false, first: false, jug: false },
  { num: 'J', color: 'red', open: false, first: false, jug: false },
  { num: 'Q', color: 'red', open: false, first: false, jug: false },
  { num: 'K', color: 'red', open: false, first: false, jug: false },
];
